Understand the Data (Exploration)

1. Load and inspect the dataset (df.info(), df.head(), df.describe()).

Identify:

2. Feature types (numerical, categorical, datetime, text)

3. Target variable

4. Data size and structure

5. Imbalanced classes or skewed distributions

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats, optimize, integrate, linalg

Reading the dataset

In [ ]:
df1 = pd.read_csv('/content/Crash.csv')
df1['Accident']=1
df2 = pd.read_csv('/content/non_accident_raleigh.csv')
df2['Accident']=0

concatenating the two datasets

In [ ]:
df = pd.concat([df1,df2],axis=0,ignore_index=True)

Inspecting the dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79893 entries, 0 to 79892
Data columns (total 49 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   X                          78866 non-null  float64
 1   Y                          78866 non-null  float64
 2   OBJECTID                   78892 non-null  float64
 3   key_crash                  78892 non-null  float64
 4   DateOfCrash                79892 non-null  object
 5   LocalUse                   78892 non-null  object
 6   LocationRelationToRoad     78888 non-null  object
 7   LocationInNearIndicator    78892 non-null  object
 8   LocationCity               79892 non-null  object
 9   LocationRoadNameOn         78892 non-null  object
 10  LocationRampIndicator      78892 non-null  object
 11  LocationFeetFromRoad       73475 non-null  float64
 12  LocationMilesFromRoad      5232 non-null   float64
 13  LocationDirectionFromRoad  64335 non-null  object
 14  LocationAtFromIndicator    78707 non-null  object
 15  LocationRoadNameAt         78706 non-null  object
 16  LocationDirectionToRoad    76884 non-null  object
 17  LocationRoadNameTo         76875 non-null  object
 18  FirstHarmfulEvent          79891 non-null  object
 19  MostHarmfulEvent           78892 non-null  object
 20  RoadClassification         78612 non-null  object
 21  RoadFeature                79665 non-null  object
 22  TrafficControlType         78781 non-null  object
 23  WeatherCondition1          79888 non-null  object
 24  WeatherCondition2          2636 non-null   object
 25  WeatherContributedToCrash  78888 non-null  object
 26  UpdateDate                 78892 non-null  object
 27  Crash_Date_Day             78892 non-null  float64
 28  Crash_Date_DOW             79892 non-null  object
 29  Crash_Date_DOW_Num         78892 non-null  float64
 30  Crash_Date_Hour            79892 non-null  float64
 31  Crash_Date_Month           79892 non-null  object
 32  Crash_Date_Month_Num       78892 non-null  float64
 33  Crash_Date_Year            79892 non-null  float64
 34  drivers                    78892 non-null  float64
 35  passengers                 78892 non-null  float64
 36  pedestrians                78502 non-null  float64
 37  pedalcyclists              78500 non-null  float64
 38  other_person_type          78494 non-null  float64
 39  unknown_person_type        78892 non-null  float64
 40  killed                     79494 non-null  float64
 41  type_a_injury              79890 non-null  float64
 42  type_b_injury              79892 non-null  float64
 43  type_c_injury              79892 non-null  float64
 44  no_injury                  79892 non-null  float64
 45  injury_unknown             78892 non-null  float64
 46  LocationLatitude           79892 non-null  float64
 47  LocationLongitude          79892 non-null  float64
 48  Accident                   79893 non-null  int64
dtypes: float64(25), int64(1), object(23)
memory usage: 29.9+ MB

In [ ]:
df.head()

,X,Y,OBJECTID,key_crash,DateOfCrash,LocalUse,LocationRelationToRoad,LocationInNearIndicator,LocationCity,LocationRoadNameOn,...,unknown_person_type,killed,type_a_injury,type_b_injury,type_c_injury,no_injury,injury_unknown,LocationLatitude,LocationLongitude,Accident
0,-8.753864e+06,4.282020e+06,1.0,121838.0,2015/01/01 06:42:00+00,P15000024,On Roadway (Surface) / Off Roadway,In,RALEIGH,LYNN RD,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,35.8647,-78.6373,1
1,-8.746306e+06,4.273095e+06,2.0,121840.0,2015/01/01 08:07:00+00,P15000038,Outside Trafficway,In,RALEIGH,3955 NEW BERN AVE,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,35.7997,-78.5694,1
2,-8.746473e+06,4.280097e+06,3.0,121843.0,2015/01/01 09:32:00+00,P15000054,On Roadway (Surface) / Off Roadway,In,RALEIGH,WALLINGFORD DR,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35.8507,-78.5709,1
3,-8.760165e+06,4.274482e+06,4.0,121848.0,2015/01/01 07:23:00+00,P15000030,On Roadway (Surface) / Off Roadway,In,RALEIGH,440,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35.8098,-78.6939,1
4,-8.760399e+06,4.285427e+06,5.0,121850.0,2015/01/01 08:59:00+00,P15000055,On Roadway (Surface) / Off Roadway,In,RALEIGH,RAY RD,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35.8895,-78.6960,1

In [ ]:
df.describe()

,X,Y,OBJECTID,key_crash,LocationFeetFromRoad,LocationMilesFromRoad,Crash_Date_Day,Crash_Date_DOW_Num,Crash_Date_Hour,Crash_Date_Month_Num,...,unknown_person_type,killed,type_a_injury,type_b_injury,type_c_injury,no_injury,injury_unknown,LocationLatitude,LocationLongitude,Accident
count,7.886600e+04,7.886600e+04,78892.000000,78892.000000,73475.000000,5232.000000,78892.000000,78892.000000,79892.000000,78892.000000,...,78892.000000,79494.000000,79890.000000,79892.000000,79892.000000,79892.000000,78892.000000,79892.000000,79892.000000,79893.000000
mean,-8.754274e+06,4.275573e+06,39447.443999,161934.137150,257.045267,0.364568,15.563112,4.152538,13.728008,6.394818,...,0.068245,0.001145,0.006146,0.053635,0.218670,2.009325,0.054999,35.877859,-78.195130,0.987483
std,6.425247e+03,1.665817e+04,22775.234613,23162.192162,488.335216,0.392609,8.751419,1.872074,5.045491,3.546182,...,0.252519,0.036326,0.089643,0.286665,0.646155,1.782198,0.250599,2.710572,4.875376,0.111177
min,-8.774669e+06,4.200000e+01,1.000000,121838.000000,0.000000,0.010000,1.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-91.282800,0.000000
25%,-8.758662e+06,4.270351e+06,19723.750000,141892.750000,10.000000,0.150000,8.000000,3.000000,10.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,35.779300,-78.680300,1.000000
50%,-8.753939e+06,4.274948e+06,39446.500000,161874.500000,100.000000,0.220000,15.000000,4.000000,14.000000,6.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,35.813100,-78.637100,1.000000
75%,-8.749283e+06,4.280729e+06,59171.250000,181987.250000,300.000000,0.450000,23.000000,6.000000,17.000000,10.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,35.855800,-78.593585,1.000000
max,-8.738046e+06,4.296659e+06,78895.000000,202155.000000,5250.000000,7.000000,31.000000,7.000000,23.000000,12.000000,...,2.000000,3.000000,4.000000,10.000000,26.000000,90.000000,7.000000,79.393500,0.000000,1.000000

Identifying the Features

In [ ]:
numeric_features = df.select_dtypes(include=['int64', 'float64']).columns
categorical_features = df.select_dtypes(include=['object']).columns
datetime_features = df.select_dtypes(include=['datetime64']).columns
text_features = df.select_dtypes(include=['object']).columns
boolean_features = df.select_dtypes(include=['bool']).columns

In [ ]:
print("Numeric:", numeric_features.tolist())
print("Categorical:", categorical_features.tolist())
print("Datetime:", datetime_features.tolist())
print("Boolean:", boolean_features.tolist())
print("Text:",text_features.tolist())

Numeric: ['X', 'Y', 'OBJECTID', 'key_crash', 'LocationFeetFromRoad', 'LocationMilesFromRoad', 'Crash_Date_Day', 'Crash_Date_DOW_Num', 'Crash_Date_Hour', 'Crash_Date_Month_Num', 'Crash_Date_Year', 'drivers', 'passengers', 'pedestrians', 'pedalcyclists', 'other_person_type', 'unknown_person_type', 'killed', 'type_a_injury', 'type_b_injury', 'type_c_injury', 'no_injury', 'injury_unknown', 'LocationLatitude', 'LocationLongitude', 'Accident']
Categorical: ['DateOfCrash', 'LocalUse', 'LocationRelationToRoad', 'LocationInNearIndicator', 'LocationCity', 'LocationRoadNameOn', 'LocationRampIndicator', 'LocationDirectionFromRoad', 'LocationAtFromIndicator', 'LocationRoadNameAt', 'LocationDirectionToRoad', 'LocationRoadNameTo', 'FirstHarmfulEvent', 'MostHarmfulEvent', 'RoadClassification', 'RoadFeature', 'TrafficControlType', 'WeatherCondition1', 'WeatherCondition2', 'WeatherContributedToCrash', 'UpdateDate', 'Crash_Date_DOW', 'Crash_Date_Month']
Datetime: []
Boolean: []
Text: ['DateOfCrash', 'LocalUse', 'LocationRelationToRoad', 'LocationInNearIndicator', 'LocationCity', 'LocationRoadNameOn', 'LocationRampIndicator', 'LocationDirectionFromRoad', 'LocationAtFromIndicator', 'LocationRoadNameAt', 'LocationDirectionToRoad', 'LocationRoadNameTo', 'FirstHarmfulEvent', 'MostHarmfulEvent', 'RoadClassification', 'RoadFeature', 'TrafficControlType', 'WeatherCondition1', 'WeatherCondition2', 'WeatherContributedToCrash', 'UpdateDate', 'Crash_Date_DOW', 'Crash_Date_Month']

In [ ]:
print(max(df['LocationLatitude']))
print(min(df['LocationLatitude']))
print(max(df['LocationLongitude']))
print(min(df['LocationLongitude']))

79.3935
0.0
0.0
-91.2828

Let us start by selecting target variable

In [ ]:
X = df.drop('Accident', axis=1)
Y = df['Accident']

In [ ]:
print("Features:")
print(X.head())
print("Target Variable:")
print(Y.head())

Features:
              X             Y  OBJECTID  key_crash             DateOfCrash  \
0 -8.753864e+06  4.282020e+06       1.0   121838.0  2015/01/01 06:42:00+00
1 -8.746306e+06  4.273095e+06       2.0   121840.0  2015/01/01 08:07:00+00
2 -8.746473e+06  4.280097e+06       3.0   121843.0  2015/01/01 09:32:00+00
3 -8.760165e+06  4.274482e+06       4.0   121848.0  2015/01/01 07:23:00+00
4 -8.760399e+06  4.285427e+06       5.0   121850.0  2015/01/01 08:59:00+00

    LocalUse              LocationRelationToRoad LocationInNearIndicator  \
0  P15000024  On Roadway (Surface) / Off Roadway                      In
1  P15000038                  Outside Trafficway                      In
2  P15000054  On Roadway (Surface) / Off Roadway                      In
3  P15000030  On Roadway (Surface) / Off Roadway                      In
4  P15000055  On Roadway (Surface) / Off Roadway                      In

  LocationCity LocationRoadNameOn  ... other_person_type  unknown_person_type  \
0      RALEIGH            LYNN RD  ...               0.0                  0.0
1      RALEIGH  3955 NEW BERN AVE  ...               0.0                  0.0
2      RALEIGH     WALLINGFORD DR  ...               0.0                  0.0
3      RALEIGH                440  ...               0.0                  0.0
4      RALEIGH             RAY RD  ...               0.0                  0.0

   killed type_a_injury type_b_injury type_c_injury no_injury injury_unknown  \
0     0.0           0.0           0.0           0.0       2.0            0.0
1     0.0           0.0           0.0           0.0       3.0            0.0
2     0.0           0.0           0.0           0.0       1.0            0.0
3     0.0           0.0           0.0           0.0       1.0            0.0
4     0.0           0.0           0.0           0.0       1.0            0.0

  LocationLatitude LocationLongitude
0          35.8647          -78.6373
1          35.7997          -78.5694
2          35.8507          -78.5709
3          35.8098          -78.6939
4          35.8895          -78.6960

[5 rows x 48 columns]
Target Variable:
0    1
1    1
2    1
3    1
4    1
Name: Accident, dtype: int64

Let us check the data size and structure of features

In [ ]:
X.shape

(79893, 48)

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79893 entries, 0 to 79892
Data columns (total 48 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   X                          78866 non-null  float64
 1   Y                          78866 non-null  float64
 2   OBJECTID                   78892 non-null  float64
 3   key_crash                  78892 non-null  float64
 4   DateOfCrash                79892 non-null  object
 5   LocalUse                   78892 non-null  object
 6   LocationRelationToRoad     78888 non-null  object
 7   LocationInNearIndicator    78892 non-null  object
 8   LocationCity               79892 non-null  object
 9   LocationRoadNameOn         78892 non-null  object
 10  LocationRampIndicator      78892 non-null  object
 11  LocationFeetFromRoad       73475 non-null  float64
 12  LocationMilesFromRoad      5232 non-null   float64
 13  LocationDirectionFromRoad  64335 non-null  object
 14  LocationAtFromIndicator    78707 non-null  object
 15  LocationRoadNameAt         78706 non-null  object
 16  LocationDirectionToRoad    76884 non-null  object
 17  LocationRoadNameTo         76875 non-null  object
 18  FirstHarmfulEvent          79891 non-null  object
 19  MostHarmfulEvent           78892 non-null  object
 20  RoadClassification         78612 non-null  object
 21  RoadFeature                79665 non-null  object
 22  TrafficControlType         78781 non-null  object
 23  WeatherCondition1          79888 non-null  object
 24  WeatherCondition2          2636 non-null   object
 25  WeatherContributedToCrash  78888 non-null  object
 26  UpdateDate                 78892 non-null  object
 27  Crash_Date_Day             78892 non-null  float64
 28  Crash_Date_DOW             79892 non-null  object
 29  Crash_Date_DOW_Num         78892 non-null  float64
 30  Crash_Date_Hour            79892 non-null  float64
 31  Crash_Date_Month           79892 non-null  object
 32  Crash_Date_Month_Num       78892 non-null  float64
 33  Crash_Date_Year            79892 non-null  float64
 34  drivers                    78892 non-null  float64
 35  passengers                 78892 non-null  float64
 36  pedestrians                78502 non-null  float64
 37  pedalcyclists              78500 non-null  float64
 38  other_person_type          78494 non-null  float64
 39  unknown_person_type        78892 non-null  float64
 40  killed                     79494 non-null  float64
 41  type_a_injury              79890 non-null  float64
 42  type_b_injury              79892 non-null  float64
 43  type_c_injury              79892 non-null  float64
 44  no_injury                  79892 non-null  float64
 45  injury_unknown             78892 non-null  float64
 46  LocationLatitude           79892 non-null  float64
 47  LocationLongitude          79892 non-null  float64
dtypes: float64(25), object(23)
memory usage: 29.3+ MB

In [ ]:
X.describe(include='all')

,X,Y,OBJECTID,key_crash,DateOfCrash,LocalUse,LocationRelationToRoad,LocationInNearIndicator,LocationCity,LocationRoadNameOn,...,other_person_type,unknown_person_type,killed,type_a_injury,type_b_injury,type_c_injury,no_injury,injury_unknown,LocationLatitude,LocationLongitude
count,7.886600e+04,7.886600e+04,78892.000000,78892.000000,79892,78892,78888,78892,79892,78892,...,78494.000000,78892.000000,79494.000000,79890.000000,79892.000000,79892.000000,79892.000000,78892.000000,79892.000000,79892.000000
unique,NaN,NaN,NaN,NaN,76719,78869,5,2,30,10033,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,2015/02/24 15:53:00+00,P15054189,On Roadway (Surface) / Off Roadway,In,RALEIGH,440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,5,2,63799,78851,78814,4846,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,-8.754274e+06,4.275573e+06,39447.443999,161934.137150,NaN,NaN,NaN,NaN,NaN,NaN,...,0.002293,0.068245,0.001145,0.006146,0.053635,0.218670,2.009325,0.054999,35.877859,-78.195130
std,6.425247e+03,1.665817e+04,22775.234613,23162.192162,NaN,NaN,NaN,NaN,NaN,NaN,...,0.051919,0.252519,0.036326,0.089643,0.286665,0.646155,1.782198,0.250599,2.710572,4.875376
min,-8.774669e+06,4.200000e+01,1.000000,121838.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-91.282800
25%,-8.758662e+06,4.270351e+06,19723.750000,141892.750000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,35.779300,-78.680300
50%,-8.753939e+06,4.274948e+06,39446.500000,161874.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,35.813100,-78.637100
75%,-8.749283e+06,4.280729e+06,59171.250000,181987.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,35.855800,-78.593585
max,-8.738046e+06,4.296659e+06,78895.000000,202155.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,2.000000,3.000000,4.000000,10.000000,26.000000,90.000000,7.000000,79.393500,0.000000

In [ ]:
print(X.isnull().sum())

X                             1027
Y                             1027
OBJECTID                      1001
key_crash                     1001
DateOfCrash                      1
LocalUse                      1001
LocationRelationToRoad        1005
LocationInNearIndicator       1001
LocationCity                     1
LocationRoadNameOn            1001
LocationRampIndicator         1001
LocationFeetFromRoad          6418
LocationMilesFromRoad        74661
LocationDirectionFromRoad    15558
LocationAtFromIndicator       1186
LocationRoadNameAt            1187
LocationDirectionToRoad       3009
LocationRoadNameTo            3018
FirstHarmfulEvent                2
MostHarmfulEvent              1001
RoadClassification            1281
RoadFeature                    228
TrafficControlType            1112
WeatherCondition1                5
WeatherCondition2            77257
WeatherContributedToCrash     1005
UpdateDate                    1001
Crash_Date_Day                1001
Crash_Date_DOW                   1
Crash_Date_DOW_Num            1001
Crash_Date_Hour                  1
Crash_Date_Month                 1
Crash_Date_Month_Num          1001
Crash_Date_Year                  1
drivers                       1001
passengers                    1001
pedestrians                   1391
pedalcyclists                 1393
other_person_type             1399
unknown_person_type           1001
killed                         399
type_a_injury                    3
type_b_injury                    1
type_c_injury                    1
no_injury                        1
injury_unknown                1001
LocationLatitude                 1
LocationLongitude                1
dtype: int64

In [ ]:
print(X.duplicated().sum())

0

Let us check for any unbalanced classes

In [ ]:
print(Y.value_counts(normalize=True) * 100)

Accident
1    98.748326
0     1.251674
Name: proportion, dtype: float64

this is shows that dataset is unbalanced with lot of accident data compared non-accident data